version: "3.4"

networks:
  frontend:
  backend:

services:
  web:
    image: nginx:latest
    container_name: docky-web
    volumes:
      - ../data/web/default.conf.template:/etc/nginx/templates/default.conf.template
      - ../data/web/index.html:/var/www/index.html
    ports:
      - 8080:8080
    environment:
      - NGINX_PORT=8080
    networks:
      - frontend
      - backend
    depends_on:
      - api

  api:
    build: ../images/api/
    image: docky-api
    container_name: docky-api
    command: uvicorn --host 0.0.0.0 --port 8081 --workers 4 "api:app"
    volumes:
      - ../data/db/database.ini:/api/data/database.ini
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres
    container_name: docky-db
    hostname: postgres
    volumes:
      - ../data/db/data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
